// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVi9FnokCLnTKZ8E_w5pWa7hpJ3sKgjc8',
    appId: '1:955787758556:web:cf1a304d82bff19b365d19',
    messagingSenderId: '955787758556',
    projectId: 'app88trans',
    authDomain: 'app88trans.firebaseapp.com',
    storageBucket: 'app88trans.firebasestorage.app',
    measurementId: 'G-W9CJHDXYK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrewBQXb-EwKOM8IkMuAwrxWGP5uJTbc',
    appId: '1:955787758556:android:2494c4ed923de223365d19',
    messagingSenderId: '955787758556',
    projectId: 'app88trans',
    storageBucket: 'app88trans.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsaTB7fQEAaqMvzn5pVcDVelTv_aq1W_U',
    appId: '1:955787758556:ios:57889a4438785b57365d19',
    messagingSenderId: '955787758556',
    projectId: 'app88trans',
    storageBucket: 'app88trans.firebasestorage.app',
    androidClientId: '955787758556-36cr0p7a48kcpian9hasq9leti2fc3bv.apps.googleusercontent.com',
    iosClientId: '955787758556-b1rjvhakttfcrcu81p71nvf9slhkifmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app88trans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsaTB7fQEAaqMvzn5pVcDVelTv_aq1W_U',
    appId: '1:955787758556:ios:57889a4438785b57365d19',
    messagingSenderId: '955787758556',
    projectId: 'app88trans',
    storageBucket: 'app88trans.firebasestorage.app',
    androidClientId: '955787758556-36cr0p7a48kcpian9hasq9leti2fc3bv.apps.googleusercontent.com',
    iosClientId: '955787758556-b1rjvhakttfcrcu81p71nvf9slhkifmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app88trans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVi9FnokCLnTKZ8E_w5pWa7hpJ3sKgjc8',
    appId: '1:955787758556:web:e78efd8bdcb61db6365d19',
    messagingSenderId: '955787758556',
    projectId: 'app88trans',
    authDomain: 'app88trans.firebaseapp.com',
    storageBucket: 'app88trans.firebasestorage.app',
    measurementId: 'G-39788NWRD8',
  );
}
